/** @format */

import bcrypt from "bcryptjs";

const users = [
  {
    userName: "Admin",
    userEmail: "admin@example.com",
    password: bcrypt.hashSync("AP231!", 10),
    role: "admin",
    phoneNumber: "0987654321",
    biography: null,
    status: "active",
  },
  {
    userName: "Quản Lý A",
    userEmail: "managerA@example.com",
    password: bcrypt.hashSync("MP456@", 10),
    role: "manager",
    phoneNumber: null,
    biography: null,
    status: "active",
  },
  {
    userName: "Nguyễn Văn B",
    userEmail: "vanb@gmail.com",
    password: bcrypt.hashSync("VP789#", 10),
    role: "volunteer",
    phoneNumber: "0912345678",
    biography: null,
    status: "active",
  },
  {
    userName: "Nguyễn Văn C",
    userEmail: "vanc@outlook.com",
    password: bcrypt.hashSync("IP123!", 10),
    role: "volunteer",
    phoneNumber: "0355123456",
    biography: null,
    status: "inactive",
  },
  {
    userName: "Tình Nguyện Viên Dũng",
    userEmail: "Dungnguyen@gmail.com",
    password: bcrypt.hashSync("MP123$", 10),
    phoneNumber: "0981234567",
    biography: null,
    role: "volunteer",
    status: "active",
  },
  {
    userName: "Quản Lý B (Kẻ Xâm Nhập)",
    userEmail: "managerB@example.com",
    password: bcrypt.hashSync("MP456@", 10), // Pass: MP456@
    role: "manager",
    phoneNumber: "0902222222",
    biography: null,
    status: "active",
  },
  ...[
    "Nguyễn Thị Lan Anh",
    "Trần Văn Hoàng Nam",
    "Lê Thị Ngọc Mai",
    "Phạm Minh Quân",
    "Đỗ Thị Hồng Nhung",
    "Vũ Hoàng Long",
    "Bùi Thị Thu Trang",
    "Hoàng Văn Đức",
    "Ngô Thị Kim Oanh",
    "Đặng Văn Hùng",
    "Phan Thị Yến Nhi",
    "Lý Văn Khánh",
    "Hà Thị Minh Thư",
    "Trương Quốc Bảo",
    "Mai Văn Tiến",
    "Chu Thị Diệu Linh",
    "Tô Ngọc Ánh",
    "Đinh Văn Sơn Tùng",
    "Cao Thị Phương",
    "Lâm Văn Huy",
    "Huỳnh Thị Bảo Châu",
    "Võ Minh Triết",
    "Kiều Anh Dũng",
    "Thái Thị Hồng Ngọc",
    "Hồ Văn Khôi",
  ].map((name) => ({
    userName: name,
    userEmail: `${name.toLowerCase().replace(/ /g, ".")}@gmail.com`,
    password: bcrypt.hashSync("Vol123!", 10),
    role: "volunteer",
    phoneNumber: "09" + Math.floor(100000000 + Math.random() * 900000000),
    biography: null,
    status: "active",
  })),
  {
    userName: "Ứng Viên Quản Lý Xuân",
    userEmail: "xuan.apply@example.com",
    password: bcrypt.hashSync("Apply123", 10),
    role: "volunteer",
    phoneNumber: "0918765432",
    biography: "Có 2 năm kinh nghiệm tổ chức sự kiện cộng đồng.",
    status: "active",
  },
  {
    userName: "Tình Nguyện Viên Hồng",
    userEmail: "hong.volunteer@example.com",
    password: bcrypt.hashSync("Volun!456", 10),
    role: "volunteer",
    phoneNumber: "0357951357",
    biography: null,
    status: "active",
  },

  {
    userName: "Quản Lý Thanh",
    userEmail: "managerThanh@example.com",
    password: bcrypt.hashSync("Thanh!789", 10),
    role: "manager",
    phoneNumber: "0909090909",
    biography: "Chuyên quản lý các sự kiện môi trường.",
    status: "active",
  },
];

export default users;
